### ISSUE TITLE
Dependecy: use newer nuSOAP library

### ISSUE THREAD

**Issue by f3l1x** [Yousign/yousign-api-client-php#21]
Hi, I'm maintainer of https://github.com/pwnlabs/nusoap package. I would appreciate if you could test this newer library in your bundle. I am trying to build one rock solid library providing nuSOAP.

**Comment by ke20** [comment]
Hi @f3l1x, 

I'm sorry but the version with nusoap is deprecated and the entire library will be soon deprecated too.

This api client is for the first version of Yousign, but now, the first version is deprecated and all client are invited to use the second version with a REST api.

But, you can fork this repository to make some tests with your new version of nusoap.

**Comment by f3l1x** [comment]
Oh, I see, thanks.
