### ISSUE TITLE
SoapClient and authentication headers

### ISSUE THREAD

**Issue by matthieuauger** [Yousign/yousign-api-client-php#6]
Hi,

I'm currently working on the integration of SoapClient in the API client.

This doesn't work, and I think this is due to the authentication headers.
The documentation ask to send theses headers
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:yous="http://www.yousign.com" xmlns:aut="http://authenticationejb.yousign.com/">
   <soapenv:Header>
      <username>YOUR_USERNAME</username>
      <password>YOUR_PASSWORD</password>
      <apikey>YOUR_APIKEY</apikey>
   </soapenv:Header>
   <soapenv:Body>
      <yous:connect/>
   </soapenv:Body>
</soapenv:Envelope>
```

But the [soap heade specification](http://www.w3schools.com/webservices/ws_soap_header.asp) and the [SoapHeader](http://php.net/manual/fr/soapheader.construct.php) class don't allow an empty namespace, it is mandatory.

Did you already success to connect to your Soap WebService with the PHP SoapClient ? Do you plan to add namespaces to the authentications headers ?

Thanks

**Comment by ke20** [comment]
Hi, 

I'm really sorry for my late answer.
Do you have solved your problem.

If no, I made a test with SoapClient, and as you said there is no namespace for the header.
But you can add a parent and put inside a fake namespace like as below :

```php
$wsdl = 'yousign_api_wsdl_url'; // @see http://developer.yousign.fr/
$soapClient = new \SoapClient($wsdl);

$authentication = new \stdClass();
$authentication->apikey 	= 'your_apikey';
$authentication->username 	= 'your_username';
$authentication->password 	= 'your_encrypted_password'; // (cf doc: sha1(sha1(clearPassword)+sha1(clearPassword)) )

// The name of namespace and parent are not fixed, you can put as you want 
$header = new \SoapHeader('http://www.yousign.com', 'Auth', $authentication);
$soapClient->__setSoapHeaders($header);

$soapClient->__call('connect', array()); // should be return true
```

**Comment by YsAdmin** [comment]
Bonjour Yousign/yousign-api-client-php, 

 Merci pour votre message, nous vous répondrons dans les meilleurs délais. Le numéro de ticket associé à votre demande est : 7087825.

L'équipe Yousign
